import matplotlib.pyplot as plt
import numpy as np
import os
path=r'G:\Deep learning\Datasets_organized\small_dataset'
spleen_image= np.load(os.path.join(path ,'Spleen/Validation/0_slice_15.npy'))
prostate_image = np.load(os.path.join(path, 'Prostate/Validation/1_slice_13.npy'))
pancreas_image=np.load(os.path.join(path, 'Pancreas/Validation/1_slice_25.npy'))
lits_image = np.load(os.path.join(path, 'Lits/Validation/0_slice_152.npy'))
hepatic_vessel_image = np.load(os.path.join(path, 'Hepatic Vessel/Validation/0_slice_29.npy'))
left_atrial = np.load(os.path.join(path, 'Left Atrial/Validation/0_slice_50.npy'))
brain_image = np.load(os.path.join(path, 'BRATS/Validation/0_slice_50.npy'))


spleen_image_label = np.load(os.path.join(path, 'Spleen/Validation_Labels/0_slice_15.npy'))
prostate_image_label = np.load(os.path.join(path, 'Prostate/Validation_Labels/1_slice_13.npy'))
pancreas_image_label = np.load(os.path.join(path, 'Pancreas/Validation_Labels/1_slice_25.npy'))
lits_image_label = np.load(os.path.join(path, 'Lits/Validation_Labels/0_slice_152.npy'))
hepatic_vessel_image_label = np.load(os.path.join(path, 'Hepatic Vessel/Validation_Labels/0_slice_29.npy'))
left_atrial_label =np.load( os.path.join(path, 'Left Atrial/Validation_Labels/0_slice_50.npy'))
brain_image_label = np.load(os.path.join(path, 'BRATS/Validation_labels/0_slice_50.npy'))

plt.subplot(3,3,1)
plt.imshow(spleen_image[1,:,:], cmap="gray")
plt.subplot(3,3,2)
plt.imshow(pancreas_image[1,:,:], cmap="gray")
plt.subplot(3,3,3)
plt.imshow(prostate_image[1,:,:], cmap="gray")
plt.subplot(3,3,4)
plt.imshow(left_atrial[1,:,:], cmap="gray")
plt.subplot(3,3,5)
plt.imshow(hepatic_vessel_image[1,:,:], cmap="gray")
plt.subplot(3,3,6)
plt.imshow(lits_image[1,:,:], cmap="gray")
plt.subplot(3,3,7)
plt.imshow(brain_image[1,:,:], cmap="gray")
plt.show()

plt.subplot(3,3,1)
plt.imshow(spleen_image_label, cmap="gray")
plt.subplot(3,3,2)
plt.imshow(pancreas_image_label, cmap="gray")
plt.subplot(3,3,3)
plt.imshow(prostate_image_label, cmap="gray")
plt.subplot(3,3,4)
plt.imshow(left_atrial_label, cmap="gray")
plt.subplot(3,3,5)
plt.imshow(hepatic_vessel_image_label, cmap="gray")
plt.subplot(3,3,6)
plt.imshow(lits_image_label, cmap="gray")
plt.subplot(3,3,7)
plt.imshow(brain_image_label, cmap="gray")
plt.show()
